#!/usr/bin/env python

import sys
import argparse
import pandas as pd
import parliament

parser = argparse.ArgumentParser()

parser.add_argument('input')
parser.add_argument('--name', default='name')
parser.add_argument('--votes', default='votes')
parser.add_argument('--seats', default='seats')
parser.add_argument('--sep', default=',')
parser.add_argument('--floatfmt', default='.4f')
parser.add_argument('--out', default=sys.stdout, type=argparse.FileType('w'))

args = parser.parse_args()

data = pd.read_csv(args.input, sep=args.sep, usecols=[args.name, args.votes, args.seats])
hor = parliament.read.hor_from_df(data, name=args.name, votes=args.votes, seats=args.seats)


print(hor.describe(floatfmt=args.floatfmt), file=args.out)
